config/routes.rb
Rails.application.routes.draw do # The priority is based upon order of creation: first created -> highest priority.

  root :to => "collections#index"

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'login'
      post 'login'
      get 'register'
      post 'register'
      delete 'logout'
      get 'me'
      get 'edit_me'
      patch 'update_me'
      get 'destroy_me'
      delete 'do_destroy_me'
      patch 'accept_membership'
      delete 'cancel_membership'
      get 'activate'
      get 'start_password_reset'
      post 'do_start_password_reset'
      get 'reset_password'
      post 'do_reset_password'
      get 'resend_activation_email'
      post 'do_resend_activation_email'
    end
    member do
      post 'ask_for_contact'
    end
  end

  resources :collections do
    collection do
      get 'own'
      get 'shared'
      get 'public'
      get 'own_list'
      get 'shared_list'
      get 'public_list'
    end
    member do
      patch 'upvote'
      patch 'downvote'
      post 'add_participant'
      patch 'update_participant'
      delete 'destroy_participant'
      delete 'cancel_participation'
    end
    resources :links, except: [:index] do
      member do
        post 'add_comment'
        get 'edit_comment'
        get 'cancel_edit_comment'
        get 'comment_count'
        patch 'update_comment'
        delete 'destroy_comment'
        patch 'upvote'
        patch 'downvote'
      end
      collection do
        get 'title_on_the_fly'
      end
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :find_collection, only: [:edit, :update, :destroy, :upvote, :downvote, :add_participant, :update_participant, :destroy_participant, :cancel_participation]
  before_action :require_current_user, except: [:index, :public, :show, :public_list]

  def index
    if current_user.nil?
      @collections = LinkCollection.pub.toplevel.limit(9).to_a
    else
      @own_collections = current_user.collections.toplevel.limit(9).order(updated_at: :desc).to_a
      @viewable_collections = current_user.viewable_collections.select { |c| c.parent == nil }.sort { |c1, c2| c2.updated_at <=> c1.updated_at }.first(9)
      @public_collections = LinkCollection.pub.toplevel.order(updated_at: :desc).limit(9).to_a
    end
    add_breadcrumb 'Home'
  end

  def own
    @own_collections = current_user.collections.toplevel.order(updated_at: :desc)
    @own_collections = @own_collections.like(params[:filter]) if params[:filter]
    @own_collections = @own_collections.to_a
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Your collections'
  end

  def shared
    @viewable_collections = current_user.viewable_collections(params[:filter]).select { |c| c.parent == nil }.sort { |c1, c2| c2.updated_at <=> c1.updated_at }
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Collections shared with you'
  end

  def public
    @public_collections = LinkCollection.pub.toplevel.order(updated_at: :desc)
    @public_collections = @public_collections.like(params[:filter]) if params[:filter]
    @public_collections = @public_collections.to_a
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Public collections'
  end

  def own_list
    @own_collections = current_user.collections.toplevel.order(updated_at: :desc)
    @own_collections = @own_collections.like(params[:filter]) if params[:filter]
    @own_collections = @own_collections.to_a
    render layout: false
  end

  def shared_list
    @viewable_collections = current_user.viewable_collections(params[:filter]).select { |c| c.parent == nil }.sort { |c1, c2| c2.updated_at <=> c1.updated_at }
    render layout: false
  end

  def public_list
    @public_collections = LinkCollection.pub.toplevel.order(updated_at: :desc)
    @public_collections = @public_collections.like(params[:filter]) if params[:filter]
    @public_collections = @public_collections.to_a
    render layout: false
  end

  def new
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'New collection'
    @collection = LinkCollection.new
    @existing_collections = current_user.collections.unscoped
  end

  def create
    params[:link_collection][:user_id] = current_user.id
    @collection = LinkCollection.create(collection_params)
    if @collection.persisted?
      flash[:notice] = 'Successfully created new collection!'
      redirect_to collection_url(@collection.link_handle)
    else
      flash[:error] = "Could not create new collection: #{@collection.errors.full_messages.join(', ')}!"
      redirect_to new_collection_url
    end
  end

  def show
    add_breadcrumb 'Home', root_path
    id = params[:id].split('-')[0].to_i
    begin
      @collection = LinkCollection.unscoped.find(id)
      if current_user.blank?
        if @collection.pub?
          add_breadcrumb 'Public collections', public_collections_path
          add_breadcrumb @collection.name
        else
          render_error :forbidden
        end
      elsif @collection.user == current_user
        add_breadcrumb 'Your collections', own_collections_path
        add_breadcrumb @collection.name
      elsif @collection.link_collection_memberships.where(user: current_user).any?
        add_breadcrumb 'Collections shared with you', shared_collections_path
        add_breadcrumb @collection.name
      elsif @collection.pub?
        add_breadcrumb 'Public collections',public_collections_path
        add_breadcrumb @collection.name
      else
        render_error :forbidden
      end
    rescue ActiveRecord::RecordNotFound
      render_error :notfound
    end
  end

  def edit
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Your collections', own_collections_path
    add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    add_breadcrumb 'Edit'
    @existing_collections = current_user.collections.unscoped.where.not(id: @collection.id)
  end

  def update
    params[:link_collection][:user_id] = current_user.id
    if @collection.update(collection_params)
      flash[:notice] = 'Collection updated successfully!'
      redirect_to collection_url(@collection.link_handle)
    else
      flash[:error] = "Could not update collection: #{@collection.errors.full_messages.join(',')}"
      redirect_to edit_collection_url(@collection)
    end
  end

  def destroy
    if @collection.destroy
      flash[:success] = 'Collection deleted successfully!'
    else
      flash[:error] = 'Could not delete collection!'
    end
    redirect_to own_collections_url
  end

  def upvote
    if %w(vote comment edit owner).include?(@collection.permission_for(current_user))
      @vote = Vote.find_by(voteable: @collection, user: current_user)
      if @vote.present?
        if @vote.positive?
          @vote.destroy
        else
          @vote.positivize!
        end
      else
        @vote = Vote.create(voteable: @collection, user: current_user, positive: true)
      end
    end
    render layout: false
  end

  def downvote
    if %w(vote comment edit owner).include?(@collection.permission_for(current_user))
      @vote = Vote.find_by(voteable: @collection, user: current_user)
      if @vote.present?
        if @vote.negative?
          @vote.destroy
        else
          @vote.negativize!
        end
      else
        @vote = Vote.create(voteable: @collection, user: current_user, positive: false)
      end
    end
    render layout: false
  end

  def add_participant
    if @collection.user == current_user
      @user = User.find_by_username_or_email(params[:user_key])
      if @user != current_user
        @membership = @collection.link_collection_memberships.create(user: @user, permission: params[:permission])
        if @user.invitation_notification_enabled
          SystemMailer.invitation_notification_email(@membership).deliver
        end
        @collection.reload
      end
    end
    render layout: false
  end

  def update_participant
    begin
      if @collection.user == current_user
        @membership = @collection.link_collection_memberships.find(params[:membership_id])
        @membership.update(permission: params[:permission])
        @collection.reload
      end
      render layout: false
    rescue ActiveRecord::RecordNotFound
      render layout: false
    end
  end

  def destroy_participant
    begin
      if @collection.user == current_user
        @membership = @collection.link_collection_memberships.find(params[:membership_id])
        @membership.destroy
        @collection.reload
      end
      render layout: false
    rescue ActiveRecord::RecordNotFound
      render layout: false
    end
  end

  def cancel_participation
    m = @collection.link_collection_memberships.where(user: current_user).first
    if m.try(:destroy)
      flash[:notice] = 'Membership in collection cancelled successfully! You have to get invited again to regain it.'
      redirect_to shared_collections_url
    else
      flash[:error] = 'Could not cancel membership in collection!'
      redirect_to collection_url(@collection.link_handle)
    end
  end

  private

  def collection_params
    params.require(:link_collection).permit(:name, :description, :parent_id, :pub, :user_id)
  end

  def find_collection
    begin
      @collection = current_user.collections.unscoped.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_error :notfound
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection_row.html.haml
.row
  - if cs[0].present?
    .col-sm-4
      = render partial: 'collections/collection', locals: {c: cs[0]}
  - if cs[1].present?
    .col-sm-4
      = render partial: 'collections/collection', locals: {c: cs[1]}
  - if cs[2].present?
    .col-sm-4
      = render partial: 'collections/collection', locals: {c: cs[2]}

app/views/collections/_link.html.haml
.collection-link
  .href
    = link_to l.title, l.url
  %small.url= l.url
  .description
    = simple_format l.description
  %small.meta
    .user= link_to l.user.username, user_path(l.user.username)
    .separator= '|'
    .score
      - if %w(vote comment edit owner).include?(l.collection.permission_for(current_user))
        %a.upvote{href: '#', title: 'Upvote', data: {link_id: l.id, collection_handle: @collection.link_handle}}= l.votes.find_by(user: current_user).try(:positive?) ? icon('thumbs-up') : icon('thumbs-o-up')
        %span.value= l.score
        %a.downvote{href: '#', title: 'Downvote', data: {link_id: l.id, collection_handle: @collection.link_handle}}= l.votes.find_by(user: current_user).try(:negative?) ? icon('thumbs-down') : icon('thumbs-o-down')
      - else
        Score:
        = l.score
    .separator= '|'
    .comments
      %a{href: collection_link_path(@collection.link_handle, l.id), title: 'Comments'}= icon('comments-o')
      = l.comments.count
    - if current_user == l.user || current_user == l.collection.user
      .separator= '|'
      = link_to 'Edit', edit_collection_link_path(l.collection.link_handle, l.id), class: 'text-warning'
      .separator= '|'
      = link_to 'Delete', collection_link_path(l.collection.link_handle, l.id), data: {method: 'delete', confirm: 'Do you really want to delete this link?'}, class: 'text-danger'

app/views/collections/_own_collections.html.haml
%h3 Your collections
= render partial: 'collections_inner', locals: {collections: @own_collections, no_collections_msg: 'You have no collections yet...'}

app/views/collections/_public_collections.html.haml
%h3 Public collections
= render partial: 'collections_inner', locals: {collections: @public_collections, no_collections_msg: 'No public collections yet...'}

app/views/collections/_viewable_collections.html.haml
%h3 Collections shared with you
= render partial: 'collections_inner', locals: {collections: @viewable_collections, no_collections_msg: 'No collections shared with you yet...'}

app/views/collections/add_participant.html.haml
= render partial: 'participants', locals: {c: @collection}

app/views/collections/index.html.haml
- content_for :title do
  Collections
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- if current_user.nil?
  %h3 Public collections
  - if @collections.empty?
    .alert.alert-info No public collections yet...
  - else
    - while @collections.count > 0
      = render partial: "collection_row", locals: { cs: @collections.pop(3) }
  .row.more-btn
    .col-sm-12
      = link_to 'More', public_collections_path, class: 'btn btn-primary'
- else
  - if @own_collections.empty? && @viewable_collections.empty? && @public_collections.empty?
    .alert.alert-info No collections to show you yet...
  - else
    = render partial: 'own_collections'
    .row.more-btn
      .col-sm-12
        = link_to 'More', own_collections_path, class: 'btn btn-primary'
    = render partial: 'viewable_collections'
    .row.more-btn
      .col-sm-12
        = link_to 'More', shared_collections_path, class: 'btn btn-primary'
    = render partial: 'public_collections'
    .row.more-btn
      .col-sm-12
        = link_to 'More', public_collections_path, class: 'btn btn-primary'
  .row.add-collection-btn
    .col-sm-12
      %a.btn.btn-success{href: new_collection_path}
        = icon('plus')
        Add a collection

app/views/collections/new.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  New collection
%h2 New collection
= form_for @collection, url: collections_path, html: {class: 'form-horizontal'} do |f|
  .form-group
    .col-sm-4
      = f.label :name, 'Name:'
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-4
      = f.label :description, 'Description:'
      = f.text_area :description, rows: 5, class: 'form-control'
  .form-group
    .col-sm-4
      = f.label :parent_id, 'Parent collection:'
      = f.collection_select :parent_id, @existing_collections, :id, :name, { include_blank: 'No parent collection' }, { class: 'form-control' }
  .form-group
    .col-sm-4
      .checkbox
        %label
          = f.check_box :pub
          Public?
  .form-group
    .col-sm-4
      = submit_tag 'Create new collection', class: 'btn btn-success'

app/views/collections/own_list.html.haml
= render partial: 'own_collections'

app/views/collections/public.html.haml
- content_for :title do
  Public collections
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
= form_tag '#', class: 'search-public form-horizontal' do
  .form-group
    .col-sm-12
      = label_tag :filter, 'Search:', class: 'sr-only'
      .input-group
        .input-group-addon= icon('search')
        = text_field_tag :filter, '', class: 'form-control', placeholder: 'Search by collection name...'
.public-collections-list
  = render partial: 'public_collections'
- if current_user.present?
  .row.add-collection-btn
    .col-sm-12
      %a.btn.btn-success{href: new_collection_path}
        = icon('plus')
        Add a collection

app/views/collections/public_list.html.haml
= render partial: 'public_collections'

app/views/collections/shared.html.haml
- content_for :title do
  Collections shared with you
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
= form_tag '#', class: 'search-shared form-horizontal' do
  .form-group
    .col-sm-12
      = label_tag :filter, 'Search:', class: 'sr-only'
      .input-group
        .input-group-addon= icon('search')
        = text_field_tag :filter, '', class: 'form-control', placeholder: 'Search by collection name...'
.shared-collections-list
  = render partial: 'viewable_collections'
.row.add-collection-btn
  .col-sm-12
    %a.btn.btn-success{href: new_collection_path}
      = icon('plus')
      Add a collection

app/views/collections/update_participant.html.haml
= render partial: 'participants', locals: {c: @collection}

app/views/collections/upvote.html.haml
- if %w(vote comment edit owner).include?(@collection.permission_for(current_user))
  %a.upvote{href: '#', title: 'Upvote', data: {collection_id: @collection.id}}= @collection.votes.find_by(user: current_user).try(:positive?) ? icon('thumbs-up') : icon('thumbs-o-up')
  %span.value= @collection.score
  %a.downvote{href: '#', title: 'Downvote', data: {collection_id: @collection.id}}= @collection.votes.find_by(user: current_user).try(:negative?) ? icon('thumbs-down') : icon('thumbs-o-down')
- else
  Score:
  = @collection.score