config/routes.rb
Rails.application.routes.draw do # The priority is based upon order of creation: first created -> highest priority.

  root :to => "collections#index"

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'login'
      post 'login'
      get 'register'
      post 'register'
      delete 'logout'
      get 'me'
      get 'edit_me'
      patch 'update_me'
      get 'destroy_me'
      delete 'do_destroy_me'
      patch 'accept_membership'
      delete 'cancel_membership'
      get 'activate'
      get 'start_password_reset'
      post 'do_start_password_reset'
      get 'reset_password'
      post 'do_reset_password'
      get 'resend_activation_email'
      post 'do_resend_activation_email'
    end
    member do
      post 'ask_for_contact'
    end
  end

  resources :collections do
    collection do
      get 'own'
      get 'shared'
      get 'public'
      get 'own_list'
      get 'shared_list'
      get 'public_list'
    end
    member do
      patch 'upvote'
      patch 'downvote'
      post 'add_participant'
      patch 'update_participant'
      delete 'destroy_participant'
      delete 'cancel_participation'
    end
    resources :links, except: [:index] do
      member do
        post 'add_comment'
        get 'edit_comment'
        get 'cancel_edit_comment'
        get 'comment_count'
        patch 'update_comment'
        delete 'destroy_comment'
        patch 'upvote'
        patch 'downvote'
      end
      collection do
        get 'title_on_the_fly'
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collections, class_name: "LinkCollection", dependent: :destroy
  has_many :link_collection_memberships, dependent: :destroy
  has_many :links, dependent: :destroy
  has_secure_password
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_create :generate_activation_token
  after_create :send_activation_email

  validates :email, presence: true, uniqueness: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 8 }, allow_nil: true
  validates :activation_token, uniqueness: { allow_blank: true }
  validates :password_reset_token, uniqueness: { allow_blank: true }

  scope :like, ->(q) {where("UPPER(username) LIKE UPPER(?) OR UPPER(email) LIKE UPPER(?)", "%#{q}%", "%#{q}%",)}
  scope :active, -> {where(active: true)}
  scope :inactive, -> {where(active: false)}
  scope :with_password_reset, -> {where(password_reset_used: false)}

  def self.find_by_username_or_email(key)
    User.where("email = ? OR username = ?", key, key).first
  end

  def viewable_collections(filter = nil)
    memberships = link_collection_memberships.joins(:link_collection).where(active: true).where.not(permission: nil)
    memberships = memberships.where("UPPER(link_collections.name) LIKE UPPER(?)", "%#{filter}%") if filter
    memberships.collect { |m| m.link_collection }
  end

  def start_password_reset
    generate_password_reset_token
    self.password_reset_used = false
    save
  end

  def generate_password_reset_token
    self.password_reset_token = loop do
      token = SecureRandom.urlsafe_base64(nil, false)
      break token unless User.exists?(password_reset_token: token)
    end
  end

  def send_activation_email
    SystemMailer.activation_email(self).deliver
  end

  def generate_activation_token
    self.activation_token = loop do
      token = SecureRandom.urlsafe_base64(nil, false)
      break token unless User.exists?(activation_token: token)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, except: [:login, :logout, :register, :me, :edit_me, :update_me, :destroy_me, :do_destroy_me, :accept_membership, :cancel_membership, :activate, :start_password_reset, :do_start_password_reset, :resend_activation_email, :do_resend_activation_email, :reset_password, :do_reset_password]
  before_action :require_current_user, except: [:register, :login, :show, :activate, :start_password_reset, :do_start_password_reset, :resend_activation_email, :do_resend_activation_email, :reset_password, :do_reset_password]

  def login
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Login'
    if request.get?
      unless current_user.nil?
        redirect_to root_url and return
      end
    elsif request.post?
      @user = User.find_by_username_or_email(params[:key]).try(:authenticate, params[:password])
      if !@user.nil? && @user.active?
        session[:logged_in_user_id] = @user.id
        flash[:notice] = "Login successful!"
        redirect_to root_url and return
      else flash[:error] = "Login failed!"
      end
      render :login
    end
  end

  def logout
    session.delete(:logged_in_user_id)
    flash[:notice] = "Logout successful!"
    redirect_to root_url
  end

  def register
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Register'
    @user = User.new
    if request.post?
      @user.attributes = user_params
      if @user.save
        flash[:notice] = "Registration successful! Activation e-mail has been sent to #{@user.email}!"
        redirect_to root_path and return
      else flash[:error] = "Could not register: " + @user.errors.full_messages.join(", ") + "!"
      end
      render :register
    end
  end

  def show
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Users'
    add_breadcrumb @user.username
    @latest_collections = @user.collections.toplevel.to_a.select { |c| c.permission_for(current_user).present? }.sort { |c1, c2| c2.updated_at <=> c1.updated_at }.first(9)
  end

  def me
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Your profile'
    @pending_memberships = current_user.link_collection_memberships.inactive
  end

  def edit_me
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Your profile', me_users_path
    add_breadcrumb 'Edit'
  end

  def update_me
    u = current_user
    if u.authenticate(params[:user][:current_password])
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if u.try(:update, user_params)
        flash[:notice] = 'Your profile updated successfully!'
        redirect_to me_users_url
      else
        flash[:error] = "Could not update your profile: #{u.errors.full_messages.join(', ')}!"
        redirect_to edit_me_users_path and return
      end
    else
      flash[:error] = 'Could not update your profile: Invalid current password!'
      redirect_to edit_me_users_path
    end
  end

  def destroy_me
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Your profile', me_users_path
    add_breadcrumb 'Delete'
  end

  def do_destroy_me
    if current_user.destroy
      session.delete(:logged_in_user_id)
      flash[:notice] = 'Your profile deleted successfully!'
    else
      flash[:error] = 'Could not delete your profile!'
    end
    redirect_to root_url
  end

  def accept_membership
    begin
      @membership = current_user.link_collection_memberships.inactive.find(params[:membership_id])
      @membership.active = true
      if @membership.save
        if @membership.link_collection.user.invitation_accept_notification_enabled
          SystemMailer.invitation_accept_notification_email(@membership).deliver
        end
        flash[:notice] = 'Invitation to participate in link collection accepted successfully!'
      else
        flash[:error] = "Could not accept invitation to participate in link collection: #{@membership.errors.full_messages.join(',')}!"
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'Could not find invitation to participate in link collection!'
    end
    redirect_to me_users_path
  end

  def cancel_membership
    begin
      @membership = current_user.link_collection_memberships.inactive.find(params[:membership_id])
      if @membership.destroy
        flash[:notice] = 'Invitation to participate in link collection rejected successfully!'
      else
        flash[:error] = 'Could not reject invitation to participate in link collection!'
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = 'Could not find invitation to participate in link collection!'
    end
    redirect_to me_users_path
  end

  def activate
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url and return
    end
    @user = User.inactive.find_by_activation_token(params[:activation_token])
    if @user.present?
      @user.active = true
      if @user.save
        flash[:notice] = 'Account activated successfully!'
        redirect_to login_users_url
      else
        flash[:error] = "Could not activate account: #{@user.errors.full_messages.join(', ')}!"
        redirect_to root_url
      end
    else
      flash[:error] = 'Invalid token!'
      redirect_to root_url
    end
  end

  def start_password_reset
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Reset password'
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url
    end
  end

  def do_start_password_reset
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url and return
    end
    @user = User.active.find_by_username(params[:username])
    if @user.present? && @user.start_password_reset
      SystemMailer.reset_password_email(@user).deliver
    end
    flash[:notice] = 'If the user exists and is active the reset password email has been sent to its email address!'
    redirect_to login_users_url
  end

  def reset_password
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Reset password'
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url and return
    end
    @user = User.active.find_by(password_reset_used: false, password_reset_token: params[:password_reset_token])
    if @user.blank?
      flash[:error] = 'Bad token!'
      redirect_to root_url
    end
  end

  def do_reset_password
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url and return
    end
    @user = User.active.find_by(password_reset_used: false, password_reset_token: params[:password_reset_token])
    if @user.blank?
      flash[:error] = 'Bad token!'
      redirect_to root_url
    end
    if @user.update(password: params[:password], password_confirmation: params[:password_confirmation], password_reset_used: true)
      flash[:notice] = 'Password reset successful!'
      redirect_to login_users_url
    else
      flash[:error] = "Password reset failed: #{@user.errors.full_messages.join(',')}"
      redirect_to reset_password_users_url(password_reset_token: @user.password_reset_token)
    end
  end

  def resend_activation_email
    add_breadcrumb 'Home', root_path
    add_breadcrumb 'Resend activation email'
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url
    end
  end

  def do_resend_activation_email
    if current_user.present?
      flash[:notice] = 'You are already logged in!'
      redirect_to root_url and return
    end
    @user = User.inactive.find_by_username(params[:username])
    if @user.present?
      @user.generate_activation_token if @user.activation_token.blank?
      @user.save
      @user.send_activation_email
    end
    flash[:notice] = 'If the user exists and has not yet been activated the activation email has been sent to its email address!'
    redirect_to root_url
  end

  def ask_for_contact
    SystemMailer.ask_for_contact_email(@user, current_user).deliver
    flash[:notice] = 'Contact request sent!'
    redirect_to user_url(@user.username)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :description, :password, :password_confirmation, :invitation_notification_enabled, :invitation_accept_notification_enabled)
  end

  def find_user
    @user = User.active.find_by_username(params[:id])
    render_error :notfound if @user.blank?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy_me.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  Delete your account
%h2.text-danger Delete your account
%p By deleting your account you will remove all of your link collections from LinkUniverse and you will lose access to the collections others shared with you. This operation is permanent. Do you really want to continue?
%a.btn.btn-success{href: do_destroy_me_users_path, data: {method: 'delete'}}
  = icon('check')
  Yes, delete my account and all related data
%a.btn.btn-danger{href: me_users_path}
  = icon('times')
  No, take me back to my profile

app/views/users/edit_me.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  Edit your profile
%h2 Edit your profile
%p Profile changes will take effect only when valid current password is given!
= form_for current_user, url: update_me_users_path, method: :patch, html: { class: "form-horizontal" } do |f|
  .form-group
    .col-sm-4
      = f.label :email, "Email:"
      = f.email_field :email, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :username, "Username:"
      = f.text_field :username, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :description, "Description:"
      = f.text_area :description, rows: 10, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :password, "New password (leave blank if you don't want to change your password):"
      = f.password_field :password, value: '', class: "form-control"
  .form-group
    .col-sm-4
      = f.label :password_confirmation, "Confirm password:"
      = f.password_field :password_confirmation, value: '', class: "form-control"
  .form-group
    .col-sm-4
      .checkbox
        %label
          = f.check_box :invitation_notification_enabled
          Notification about invitation to participate in link collection
  .form-group
    .col-sm-4
      .checkbox
        %label
          = f.check_box :invitation_accept_notification_enabled
          Notification about acceptance of invitation to participate in link collection
  .form-group
    .col-sm-4
      = f.label :password, "Current password:"
      = f.password_field :current_password, value: '', class: "form-control"
  .form-group
    .col-sm-4
      = f.submit "Update profile", class: "btn btn-warning"
      = link_to "Back", me_users_path, class: "btn btn-link"

app/views/users/login.html.haml
- content_for :title do
  Login
%h2 Login
= form_tag nil, class: "form-horizontal" do
  .form-group
    .col-sm-4
      = label_tag :key, "Username or Email:"
      = text_field_tag :key, '', class: "form-control"
  .form-group
    .col-sm-4
      = label_tag :password, "Password:"
      = password_field_tag :password, '', class: "form-control"
  .form-group
    .col-sm-4
      = submit_tag "Login", class: "btn btn-primary"
.register-link
  Don't have an account yet?
  = link_to 'Register', register_users_path
.forgot-password-link
  = link_to 'Forgot your password?', start_password_reset_users_path
.resend-activation-email-link
  = link_to 'Activation email did not arrive?', resend_activation_email_users_path

app/views/users/me.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  Your profile
%h2 Your profile
%dl.dl-horizontal.your-profile-dl
  %dt Username:
  %dd= current_user.username
  %dt Email:
  %dd= current_user.email
  %dt Description:
  %dd= simple_format current_user.description
  %dt Total collections:
  %dd= current_user.collections.count
  %dt Total links:
  %dd= current_user.links.count
  %dt Total votes:
  %dd= current_user.votes.count
  %dt Total comments:
  %dd= current_user.comments.count
  %dt Invitation notification:
  %dd= current_user.invitation_notification_enabled ? 'Enabled' : 'Disabled'
  %dt Invitation acceptance notification:
  %dd= current_user.invitation_accept_notification_enabled ? 'Enabled' : 'Disabled'
%a.btn.btn-primary{href: user_path(current_user.username)}
  = icon('eye')
  Show public profile
%a.btn.btn-warning{href: edit_me_users_path}
  = icon('edit')
  Edit
%a.btn.btn-danger{href: destroy_me_users_path}
  = icon('times')
  Delete
.pending-memberships
  %h3 Invitations to participate in link collections
  - if @pending_memberships.empty?
    .alert.alert-info No invitations to participate in link collections!
  - else
    %table.table.table-stripes.table-hover.text-center
      %thead
        %tr
          %th.text-center Collection name
          %th.text-center Collection author
          %th.text-center Your permissions
          %th.text-center Actions
      %tbody
        - @pending_memberships.each do |membership|
          %tr
            %td= membership.link_collection.name
            %td= membership.link_collection.user.username
            %td= membership.link_collection.descriptive_permission_for(current_user)
            %td
              = link_to 'Accept', accept_membership_users_path(membership_id: membership.id), method: :patch, class: 'btn btn-success accept-membership'
              = link_to 'Reject', cancel_membership_users_path(membership_id: membership.id), method: :delete, class: 'btn btn-danger cancel-membership'

app/views/users/register.html.haml
- content_for :title do
  Register
%h2 Register for a free account
= form_for @user, url: register_users_path, html: { class: "form-horizontal" } do |f|
  .form-group
    .col-sm-4
      = f.label :email, "Email:"
      = f.email_field :email, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :username, "Username:"
      = f.text_field :username, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :description, "Description:"
      = f.text_area :description, rows: 10, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :password, "Password:"
      = f.password_field :password, class: "form-control"
  .form-group
    .col-sm-4
      = f.label :password_confirmation, "Confirm password:"
      = f.password_field :password_confirmation, class: "form-control"
  .form-group
    .col-sm-4
      = f.submit "Register", class: "btn btn-primary"
.login-link
  Already have an account?
  = link_to 'Login', login_users_path

app/views/users/resend_activation_email.html.haml
- content_for :title do
  Resend activation email
%h2 Resend activation email
= form_tag do_resend_activation_email_users_path, class: 'form-horizontal' do
  .form-group
    .col-sm-4
      = label_tag :username, 'Your username:'
      = text_field_tag :username, '', class: 'form-control'
  .form-group
    .col-sm-4
      = submit_tag 'Resend activation email', class: 'btn btn-primary'
.login-link
  = link_to 'Login', login_users_path

app/views/users/reset_password.html.haml
- content_for :title do
  Reset password
%h2 Reset password
= form_tag do_reset_password_users_path, class: 'form-horizontal' do
  .form-group
    .col-sm-4
      = label_tag :password, 'New password:'
      = password_field_tag :password, '', class: 'form-control'
  .form-group
    .col-sm-4
      = label_tag :password_confirmation, 'Password confirmation:'
      = password_field_tag :password_confirmation, '', class: 'form-control'
  .form-group
    .col-sm-4
      = hidden_field_tag :password_reset_token, @user.password_reset_token
      = submit_tag 'Reset password', class: 'btn btn-primary'

app/views/users/show.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  #{@user.username}'s profile
%h2 #{@user.username}'s profile
%dl.dl-horizontal
  %dt Username:
  %dd= @user.username
  %dt Description:
  %dd= simple_format @user.description
  %dt Total collections:
  %dd= @user.collections.count
  %dt Total links:
  %dd= @user.links.count
  %dt Total votes:
  %dd= @user.votes.count
  %dt Total comments:
  %dd= @user.comments.count
%h3 Last updated collections
- if @latest_collections.empty?
  .alert.alert-info No collections from this user yet!
- else
  - while @latest_collections.count > 0
    = render partial: 'collections/collection_row', locals: {cs: @latest_collections.pop(3)}
- if current_user.present?
  %a.ask-for-contact{href: ask_for_contact_user_path(@user.username), data: {method: :post}, class: 'btn btn-primary'}
    = icon('envelope-o')
    Ask for contact (send email address)

app/views/users/start_password_reset.html.haml
- content_for :title do
  Reset password
%h2 Reset password
= form_tag do_start_password_reset_users_path, class: 'form-horizontal' do
  .form-group
    .col-sm-4
      = label_tag :username, 'Your username:'
      = text_field_tag :username, '', class: 'form-control'
  .form-group
    .col-sm-4
      = submit_tag 'Send password reset instructions', class: 'btn btn-primary'
.login-link
  = link_to 'Login', login_users_path