config/routes.rb
Rails.application.routes.draw do # The priority is based upon order of creation: first created -> highest priority.

  root :to => "collections#index"

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'login'
      post 'login'
      get 'register'
      post 'register'
      delete 'logout'
      get 'me'
      get 'edit_me'
      patch 'update_me'
      get 'destroy_me'
      delete 'do_destroy_me'
      patch 'accept_membership'
      delete 'cancel_membership'
      get 'activate'
      get 'start_password_reset'
      post 'do_start_password_reset'
      get 'reset_password'
      post 'do_reset_password'
      get 'resend_activation_email'
      post 'do_resend_activation_email'
    end
    member do
      post 'ask_for_contact'
    end
  end

  resources :collections do
    collection do
      get 'own'
      get 'shared'
      get 'public'
      get 'own_list'
      get 'shared_list'
      get 'public_list'
    end
    member do
      patch 'upvote'
      patch 'downvote'
      post 'add_participant'
      patch 'update_participant'
      delete 'destroy_participant'
      delete 'cancel_participation'
    end
    resources :links, except: [:index] do
      member do
        post 'add_comment'
        get 'edit_comment'
        get 'cancel_edit_comment'
        get 'comment_count'
        patch 'update_comment'
        delete 'destroy_comment'
        patch 'upvote'
        patch 'downvote'
      end
      collection do
        get 'title_on_the_fly'
      end
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :collection, class_name: "LinkCollection"
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy
  
  before_save :ensure_correct_url, :ensure_title
  
  validates :url, uniqueness: { scope: :collection, message: "should be unique inside collection" }
  validates :title, uniqueness: { scope: :collection, message: "should be unique inside collection" }
  validates :collection_id, presence: true
  validates :user_id, presence: true
  
  scope :like, ->(q) { where("UPPER(title) LIKE UPPER(?) OR UPPER(url) LIKE UPPER(?)", "%#{q}%", "%#{q}%") }
  
  def fetch_title!
    t = nil
    begin
      if HTTParty.head(self.url).content_type == "text/html"
        HTTParty.get(self.url).lines.each do |line|
          /(<title[^>]*>|<TITLE[^>]*>)(.*)(<\/title>|<\/TITLE>)/.match(line) do |md|
            t = md[2] if t.blank?
          end
        end
      end
    rescue
      t = nil
    end
    self.title = t if !t.nil? && !t.empty?
  end

  def score
    votes.positive.count - votes.negative.count
  end

  private
  
  def ensure_title
    if self.title.nil? || self.title.empty?
      self.fetch_title!
      if self.title.nil? || self.title.empty?
        self.title = self.url
      end
    end
  end
  
  def ensure_correct_url
    HTTParty.head(self.url)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_current_user, except: :show
  before_action :find_collection
  before_action :find_link, except: [:new, :create, :title_on_the_fly]

  def new
    render_error :forbidden unless @collection.user == current_user || @collection.permission_for(current_user) == 'edit'
    add_breadcrumb 'Home', root_path
    if @collection.user == current_user
      add_breadcrumb 'Your collections', own_collections_path
      add_breadcrumb @collection.name, collection_url(@collection.link_handle)
    elsif @collection.permission_for(current_user) == 'edit'
      add_breadcrumb 'Collections shared with you', shared_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    else
      render_error :forbidden
    end
    add_breadcrumb 'Add link'
    @link = @collection.links.new
  end

  def create
    render_error :forbidden unless @collection.user == current_user || @collection.permission_for(current_user) == 'edit'
    params[:link][:user_id] = current_user.id
    @link = @collection.links.create(link_params)
    if @link.persisted?
      flash[:notice] = 'Link created successfully!'
      @collection.touch
      redirect_to collection_url(@collection.link_handle)
    else
      flash[:error] = "Could not create link: #{@link.errors.full_messages.join(', ')}"
      redirect_to new_collection_link_url(@collection.link_handle)
    end
  end

  def show
    add_breadcrumb 'Home', root_path
    if current_user.blank?
      if @collection.pub?
        add_breadcrumb 'Public collections', public_collections_path
        add_breadcrumb @collection.name, collection_path(@collection.link_handle)
      else
        render_error :forbidden
      end
    elsif @collection.user == current_user
      add_breadcrumb 'Your collections', own_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    elsif @collection.link_collection_memberships.where(user: current_user).any?
      add_breadcrumb 'Collections shared with you', shared_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    elsif @collection.pub?
      add_breadcrumb 'Public collections',public_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    else
      render_error :forbidden
    end
    add_breadcrumb @link.title
  end

  def edit
    render_error :forbidden unless current_user == @link.user || current_user == @link.collection.user
    add_breadcrumb 'Home', root_path
    if @collection.user == current_user
      add_breadcrumb 'Your collections', own_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    elsif @collection.permission_for(current_user) == 'edit'
      add_breadcrumb 'Collections shared with you', shared_collections_path
      add_breadcrumb @collection.name, collection_path(@collection.link_handle)
    end
    add_breadcrumb @link.title, collection_link_path(@collection.link_handle, @link.id)
    add_breadcrumb 'Edit'
  end

  def update
    render_error :forbidden unless current_user == @link.user || current_user == @link.collection.user
    if @link.update(link_params)
      flash[:notice] = 'Link updated successfully!'
      @collection.touch
      redirect_to collection_url(@collection.link_handle)
    else
      flash[:notice] = "Could not update link: #{@link.errors.full_messages.join(',')}!"
      redirect_to edit_collection_link_url(@collection.link_handle, @link.id)
    end
  end

  def destroy
    render_error :forbidden unless current_user == @link.user || current_user == @link.collection.user
    if @link.destroy
      flash[:notice] = 'Link deleted successfully!'
    else
      flash[:error] = 'Could not delete link!'
    end
    redirect_to collection_url(@collection.link_handle)
  end

  def upvote
    if @collection.user == current_user || @link.user == current_user || %w(vote comment edit owner).include?(@collection.permission_for(current_user))
      @vote = Vote.find_by(voteable: @link, user: current_user)
      if @vote.present?
        if @vote.positive?
          @vote.destroy
        else
          @vote.positivize!
        end
      else
        @vote = Vote.create(voteable: @link, user: current_user, positive: true)
      end
    end
    render layout: false
  end

  def downvote
    if @collection.user == current_user || @link.user == current_user || %w(vote comment edit owner).include?(@collection.permission_for(current_user))
      @vote = Vote.find_by(voteable: @link, user: current_user)
      if @vote.present?
        if @vote.negative?
          @vote.destroy
        else
          @vote.negativize!
        end
      else
        @vote = Vote.create(voteable: @link, user: current_user, positive: false)
      end
    end
    render layout: false
  end

  def add_comment
    if @link.user == current_user || @link.collection.user == current_user || %w(comment edit owner).include?(@link.collection.permission_for(current_user))
      @comment = @link.comments.create(user: current_user, content: params[:content])
    end
    render layout: false
  end

  def edit_comment
    begin
      @comment = @link.comments.find(params[:comment_id])
      if @comment.user == current_user || @link.user == current_user || @link.collection.user == current_user
        render layout: false
      else
        render :cancel_edit_comment, layout: false
      end
    rescue ActiveRecord::RecordNotFound
      render nothing: true
    end
  end

  def cancel_edit_comment
    begin
      @comment = @link.comments.find(params[:comment_id])
      render layout: false
    rescue ActiveRecord::RecordNotFound
      render nothing: true
    end
  end

  def update_comment
    begin
      @comment = @link.comments.find(params[:comment_id])
      if @comment.user == current_user || @link.user == current_user || @link.collection.user == current_user
        @comment.update(content: params[:content])
      end
      render layout: false
    rescue ActiveRecord::RecordNotFound
      render layout: false
    end
  end

  def destroy_comment
    begin
      @comment = @link.comments.find(params[:comment_id])
      if @comment.user == current_user || @link.user == current_user || @link.collection.user == current_user
        @comment.destroy
      end
      render layout: false
    rescue ActiveRecord::RecordNotFound
      render layout: false
    end
  end

  def title_on_the_fly
    tmp_link = Link.new(url: params[:link_url])
    tmp_link.fetch_title!
    if tmp_link.title.present?
      render text: tmp_link.title
    else
      render text: tmp_link.url
    end
  end

  def comment_count
    render layout: false
  end

  private

  def link_params
    params.require(:link).permit(:user_id, :title, :url, :description)
  end

  def find_collection
    collection_id = params[:collection_id].split('-')[0].to_i
    begin
      @collection = LinkCollection.unscoped.find(collection_id)
    rescue ActiveRecord::RecordNotFound
      render_error :notfound
    end
  end

  def find_link
    begin
      @link = @collection.links.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_error :notfound
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_comment.html.haml
.comment{data: {id: c.id, link_id: c.commentable.id, collection_handle: c.commentable.collection.link_handle}}
  .content.well.well-sm= simple_format c.content
  %small.meta
    .user= link_to c.user.username, user_path(c.user)
    - if c.updated_at > c.created_at
      .separator= '|'
      .edited Edited
    - if c.user == current_user || c.commentable.user == current_user || c.commentable.collection.user == current_user || c.commentable.collection.permission_for(current_user) == 'edit'
      .separator= '|'
      = link_to 'Edit', '#', class: 'text-warning edit-comment'
      .separator= '|'
      = link_to 'Delete', '#', class: 'text-danger delete-comment'

app/views/links/add_comment.html.haml
%h4 Comments
- if @link.comments.empty?
  .alert.alert-info No comments yet...
- else
  - @link.comments.each do |comment|
    = render partial: 'comment', locals: {c: comment}
- if @link.user == current_user || @link.collection.user == current_user || %w(comment edit owner).include?(@collection.permission_for(current_user))
  = form_tag add_comment_collection_link_path(@collection.link_handle, @link.id), class: 'form-horizontal add-comment-form' do
    .form-group
      .col-sm-12
        = text_area_tag :content, '', rows: 5, placeholder: 'Write a comment...', class: 'form-control'
    .form-group
      .col-sm-12
        = submit_tag 'Add comment', class: 'btn btn-success add-comment'

app/views/links/cancel_edit_comment.html.haml
= render partial: 'comment', locals: {c: @comment}

app/views/links/comment_count.html.haml
= icon('comments-o')
= @link.comments.count

app/views/links/destroy_comment.html.haml
%h4 Comments
- if @link.comments.empty?
  .alert.alert-info No comments yet...
- else
  - @link.comments.each do |comment|
    = render partial: 'comment', locals: {c: comment}
- if @link.user == current_user || @link.collection.user == current_user || %w(comment edit owner).include?(@collection.permission_for(current_user))
  = form_tag add_comment_collection_link_path(@collection.link_handle, @link.id), class: 'form-horizontal add-comment-form' do
    .form-group
      .col-sm-12
        = text_area_tag :content, '', rows: 5, placeholder: 'Write a comment...', class: 'form-control'
    .form-group
      .col-sm-12
        = submit_tag 'Add comment', class: 'btn btn-success add-comment'

app/views/links/downvote.html.haml
.score
  - if %w(vote comment edit owner).include?(@link.collection.permission_for(current_user))
    %a.upvote{href: '#', title: 'Upvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:positive?) ? icon('thumbs-up') : icon('thumbs-o-up')
    %span.value= @link.score
    %a.downvote{href: '#', title: 'Downvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:negative?) ? icon('thumbs-down') : icon('thumbs-o-down')
  - else
    Score:
    = @link.score

app/views/links/edit.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  Editing link #{@link.title} in collection #{@collection.name} by #{@collection.user.username}
%h2 Editing link #{@link.title} in collection #{@collection.name} by #{@collection.user.username}
= form_for @link, url: collection_link_path(@collection.link_handle, @link.id), html: { class: 'form-horizontal' } do |f|
  .form-group
    .col-sm-4
      = f.label :url, 'URL:'
      = f.text_field :url, class: 'form-control'
  .form-group
    .col-sm-4
      = f.label :title, 'Title (automatically resolves if empty):'
      .input-group
        = f.text_field :title, class: 'form-control'
        .input-group-addon
          %a.title-on-the-fly{href: '#', title: 'Resolve title now', data: {collection_handle: @collection.link_handle}}= icon 'arrow-down'
  .form-group
    .col-sm-4
      = f.label :description, 'Description:'
      = f.text_area :description, rows: 5, class: 'form-control'
  .form-group
    .col-sm-4
      = submit_tag 'Update link', class: 'btn btn-warning'

app/views/links/edit_comment.html.haml
= form_tag update_comment_collection_link_path(@collection.link_handle, @link.id), method: :patch, class: 'form-horizontal update-comment-form' do
  .form-group
    .col-sm-12
      = text_area_tag :content, @comment.content, rows: 5, placeholder: 'Write a comment...', class: 'form-control'
  .form-group
    .col-sm-12
      = submit_tag 'Update comment', class: 'btn btn-warning update-comment'
      = link_to 'Cancel edit comment', '#', class: 'btn btn-link cancel-edit-comment'

app/views/links/new.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  Add link to collection #{@collection.name} by #{@collection.user.username}
%h2 Add link to collection #{@collection.name} by #{@collection.user.username}
= form_for @link, url: collection_links_path(@collection.link_handle), html: { class: 'form-horizontal' } do |f|
  .form-group
    .col-sm-4
      = f.label :url, 'URL:'
      = f.text_field :url, class: 'form-control'
  .form-group
    .col-sm-4
      = f.label :title, 'Title (automatically resolves if empty):'
      .input-group
        = f.text_field :title, class: 'form-control'
        .input-group-addon
          %a.title-on-the-fly{href: '#', title: 'Resolve title now', data: {collection_handle: @collection.link_handle}}= icon 'arrow-down'
  .form-group
    .col-sm-4
      = f.label :description, 'Description:'
      = f.text_area :description, rows: 5, class: 'form-control'
  .form-group
    .col-sm-4
      = submit_tag 'Add link', class: 'btn btn-success'

app/views/links/show.html.haml
- content_for :userbox do
  = render partial: "application/userbox", locals: {u: current_user}
- content_for :title do
  #{@link.title} in collection #{@collection.name} by #{@collection.user.username}
.collection-link
  .href
    = link_to @link.title, @link.url
  %small.url= @link.url
  .description
    = simple_format @link.description
  %small.meta
    .user= link_to @link.user.username, user_path(@link.user.username)
    .separator= '|'
    .score
      - if %w(vote comment edit owner).include?(@link.collection.permission_for(current_user))
        %a.upvote{href: '#', title: 'Upvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:positive?) ? icon('thumbs-up') : icon('thumbs-o-up')
        %span.value= @link.score
        %a.downvote{href: '#', title: 'Downvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:negative?) ? icon('thumbs-down') : icon('thumbs-o-down')
      - else
        Score:
        = @link.score
    .separator= '|'
    .comments
      = icon('comments-o')
      = @link.comments.count
    - if current_user == @link.user || current_user == @link.collection.user
      .separator= '|'
      = link_to 'Edit', edit_collection_link_path(@link.collection.link_handle, @link.id), class: 'text-warning'
      .separator= '|'
      = link_to 'Delete', collection_link_path(@link.collection.link_handle, @link.id), data: {method: 'delete', confirm: 'Do you really want to delete this link?'}, class: 'text-danger'
.row
  .col-sm-4
    .collection-link-comments
      %h4 Comments
      - if @link.comments.empty?
        .alert.alert-info No comments yet...
      - else
        - @link.comments.each do |comment|
          = render partial: 'comment', locals: {c: comment}
      - if @link.user == current_user || @link.collection.user == current_user || %w(comment edit owner).include?(@collection.permission_for(current_user))
        = form_tag add_comment_collection_link_path(@collection.link_handle, @link.id), class: 'form-horizontal add-comment-form' do
          .form-group
            .col-sm-12
              = text_area_tag :content, '', rows: 5, placeholder: 'Write a comment...', class: 'form-control'
          .form-group
            .col-sm-12
              = submit_tag 'Add comment', class: 'btn btn-success add-comment'

app/views/links/update_comment.html.haml
= render partial: 'comment', locals: {c: @comment}

app/views/links/upvote.html.haml
.score
  - if %w(vote comment edit owner).include?(@link.collection.permission_for(current_user))
    %a.upvote{href: '#', title: 'Upvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:positive?) ? icon('thumbs-up') : icon('thumbs-o-up')
    %span.value= @link.score
    %a.downvote{href: '#', title: 'Downvote', data: {link_id: @link.id, collection_handle: @collection.link_handle}}= @link.votes.find_by(user: current_user).try(:negative?) ? icon('thumbs-down') : icon('thumbs-o-down')
  - else
    Score:
    = @link.score