config/routes.rb
Rails.application.routes.draw do # The priority is based upon order of creation: first created -> highest priority.

  root :to => "collections#index"

  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'login'
      post 'login'
      get 'register'
      post 'register'
      delete 'logout'
      get 'me'
      get 'edit_me'
      patch 'update_me'
      get 'destroy_me'
      delete 'do_destroy_me'
      patch 'accept_membership'
      delete 'cancel_membership'
      get 'activate'
      get 'start_password_reset'
      post 'do_start_password_reset'
      get 'reset_password'
      post 'do_reset_password'
      get 'resend_activation_email'
      post 'do_resend_activation_email'
    end
    member do
      post 'ask_for_contact'
    end
  end

  resources :collections do
    collection do
      get 'own'
      get 'shared'
      get 'public'
      get 'own_list'
      get 'shared_list'
      get 'public_list'
    end
    member do
      patch 'upvote'
      patch 'downvote'
      post 'add_participant'
      patch 'update_participant'
      delete 'destroy_participant'
      delete 'cancel_participation'
    end
    resources :links, except: [:index] do
      member do
        post 'add_comment'
        get 'edit_comment'
        get 'cancel_edit_comment'
        get 'comment_count'
        patch 'update_comment'
        delete 'destroy_comment'
        patch 'upvote'
        patch 'downvote'
      end
      collection do
        get 'title_on_the_fly'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :initialize_breadcrumbs
  include ApplicationHelper

  def render_error type
    if type.to_sym == :forbidden
      render "errors/forbidden", status: 403, layout: 'error' and return
    elsif type.to_sym == :notfound
      render "errors/notfound", status: 404, layout: 'error' and return
    end
  end

  protected

  def initialize_breadcrumbs
    @breadcrumbs = []
  end

  def require_current_user
    if current_user.blank?
      flash[:notice] = 'You have to log in to continue!'
      redirect_to login_users_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_breadcrumb name, url = nil
    if url.nil?
      @breadcrumbs << {name: name}
    else
      @breadcrumbs << {name: name, url: url}
    end
  end

  def current_user
    begin
      User.active.find(session[:logged_in_user_id])
    rescue ActiveRecord::RecordNotFound => e
      nil
    end
  end
end

app/views/application/_breadcrumbs.html.haml
- if @breadcrumbs.any?
  %ol.breadcrumb
    - @breadcrumbs.each do |crumb|
      - if @breadcrumbs.last == crumb
        %li.active= crumb[:name]
      - else
        - if crumb.keys.include?(:url)
          %li= link_to crumb[:name], crumb[:url]
        - else
          %li= crumb[:name]

app/views/application/_userbox.html.haml
.userbox
  - if u.nil?
    .status You are not logged in!
    .links
      = link_to "Login", login_users_path
      or
      = link_to "Register", register_users_path
  - else
    .status
      Welcome
      = u.username + "!"
    .links
      .link
        = link_to "Your profile", me_users_path
      .link
        = link_to "Logout", logout_users_path, method: :delete